/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef FLECS_SYSTEMS_PHYSICS_BAKE_CONFIG_H
#define FLECS_SYSTEMS_PHYSICS_BAKE_CONFIG_H

/* Generated includes are specific to the bake environment. If a project is not
 * built with bake, it will have to provide alternative methods for including
 * its dependencies. */
#ifdef __BAKE__
/* Headers of public dependencies */
#include <flecs>
#include <flecs.math>
#include <flecs.components.transform>
#include <flecs.components.geometry>
#include <flecs.components.physics>
#include <flecs.systems.transform>

/* Headers of private dependencies */
#ifdef FLECS_SYSTEMS_PHYSICS_IMPL
/* No dependencies */
#endif
#endif

/* Convenience macro for exporting symbols */
#ifndef FLECS_SYSTEMS_PHYSICS_STATIC
  #if FLECS_SYSTEMS_PHYSICS_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define FLECS_SYSTEMS_PHYSICS_EXPORT __declspec(dllexport)
  #elif FLECS_SYSTEMS_PHYSICS_IMPL
    #define FLECS_SYSTEMS_PHYSICS_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define FLECS_SYSTEMS_PHYSICS_EXPORT __declspec(dllimport)
  #else
    #define FLECS_SYSTEMS_PHYSICS_EXPORT
  #endif
#else
  #define FLECS_SYSTEMS_PHYSICS_EXPORT
#endif

#endif

